### ISSUE TITLE
Environments

### ISSUE THREAD

**Issue by Amazingren** [LuigiRiz/NOPS#4]
Hi @LuigiRiz ,

Sorry to bother you again. When I tried to reproduce your method. The Minkowski Engine seems really not easy to install (even with Conda).

To this end, may I kindly ask you to copy your coda environments if it is possible:

The process is as follows:
```
conda pack -n env_name
```
maybe you need to install 'conda-pack' first, and after this, you will get an `env_name.tar.gz` file.

Then you can share it with me.

Bests regards and many thanks,

**Comment by LuigiRiz** [comment]
Hi, 

MinkowskiEngine never gave me problems. It's a little bit tricky to install, but following their [guidelines](https://github.com/NVIDIA/MinkowskiEngine#anaconda) the installation is pretty straightforward.

I've tried to pack the conda environment as you requested , but it's far too big to be shared here (around 3GB due to the compiled CUDA code it contains). If you still have troubles in installing MinkowskiEngine following the guidelines, we can arrange a file sharing in another way.

Have a nice day

Luigi

**Comment by Amazingren** [comment]
> Hi,
> 
> MinkowskiEngine never gave me problems. It's a little bit tricky to install, but following their [guidelines](https://github.com/NVIDIA/MinkowskiEngine#anaconda) the installation is pretty straightforward.
> 
> I've tried to pack the conda environment as you requested , but it's far too big to be shared here (around 3GB due to the compiled CUDA code it contains). If you still have troubles in installing MinkowskiEngine following the guidelines, we can arrange a file sharing in another way.
> 
> Have a nice day
> 
> Luigi

Hi Luigi,

Thanks for the useful feedback and your efforts.

After carefully following the guidelines several times. The main problem from my side is the cuda.
Then I :
- 1. Install the new cuda version(11.3)
- 2. Install Pytorch 1.11.0 ( Conda install doesn't work for me, and the pip version works) with the right cuda version
- 3. Then install ME with `git clone...` and then `python setup.py ...`

And finally, it works for me!
Thanks a lot again!

Bests,
Bin
